[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
license = "MIT"
edition = "2021"

[workspace.dependencies]
okapi_js_parser = { path = "crates/okapi_js_parser" }
okapi_unicode = { path = "crates/okapi_unicode" }
