[package]
name = "hippo_ast"
version = "0.1.0"
publish               = false
edition.workspace     = true
license.workspace     = true

[dependencies]
hermes = { workspace = true }
juno_support = { workspace = true }
