[package]
name = "hippo_ast"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
oxc_allocator = "0.3.0"
oxc_ast = "0.3.0"
oxc_diagnostics = "0.3.0"
oxc_parser = "0.3.0"
oxc_span = "0.3.0"
serde_json = "1.0.108"
