[package]
name = "hippo_js_parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hippo_estree = { workspace = true }
hippo_unicode = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
