/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Token {
  tokenType: string
  value?: string
  start: number
  end: number
}
export function tokenizeSync(sourceText: string): Array<Token>
