[package]
name = "hippo_wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hippo_js_parser = { workspace = true }
wasm-bindgen = "0.2.92"
