mod array_expression;
mod assignment_expression;
mod binary_expression;
mod class_declaration;
mod conditional_expression;
mod debugger_statement;
mod empty_statement;
mod function_declaration;
mod grouping_expression;
mod identifier;
mod if_statement;
mod lexical_declaration;
mod literals;
mod logical_expression;
mod module_export;
mod module_import;
mod object_expression;
mod postfix_expression;
mod prefix_expression;
mod return_statement;
mod script;
mod this_expression;
mod while_statement;

// mod array_assignment_target;
// mod array_assignment_target_rest;
// mod array_binding;
// mod array_binding_rest;
// mod array_element_in_expression;
// mod arrow_expression_in_alternate;
// mod arrow_expression_single_param;
// mod assign_eval_member_or_computed_expression;
// mod assignment_shorthand_prop_with_initializer;
// mod assignment_target;
// mod async_arrow_expression;
// mod async_continue_statement;
// mod async_function_expression;
// mod async_ident;
// mod bom_character;
// mod call_arguments;
// mod class_decorator;
// mod class_named_abstract_is_valid_in_js;
// mod computed_member_expression;
// mod computed_member_in;
// mod computed_member_name_in;
// mod decorator_class_declaration_top_level;
// mod decorator_export_top_level;
// mod destructuring_initializer_binding;
// mod do_while_asi;
// mod do_while_statement;
// mod exponent_unary_parenthesized;
// mod for_await_async_identifier;
// mod for_in_initializer_loose_mode;
// mod for_statement;
// mod for_with_in_in_parenthesized_expression;
// mod function_expression;
// mod function_expression_id;
// mod function_identifier;
// mod function_in_if_or_labelled_statement_loose_mode;
// mod hoisted_declaration_in_single_statement_context;
// mod identifier_reference;
// mod in_expression_in_arguments;
// mod labeled_statement;
// mod labelled_function_declaration;
// mod labelled_statement_in_single_statement_context;
// mod new_expression;
// mod object_expression_generator_method;
// mod object_member_name;
// mod object_prop_in_rhs;
// mod object_prop_name;
// mod object_property_binding;
// mod object_shorthand_property;
// mod parameter_list;
// mod paren_or_arrow_expression;
// mod parenthesized_sequence_expression;
// mod pattern_with_default_in_keyword;
// mod rest_property_binding;
// mod semicolons;
// mod single_parameter_arrow_function_with_parameter_named_async;
// mod subscripts;
// mod super_expression_in_constructor_parameter_list;
// mod template_literal;
// mod throw_statement;
// mod try_statement;
// mod unary_delete;
// mod unary_delete_nested;
// mod unary_expression;
// mod yield_expression;
// mod yield_in_generator_function;
