mod array_assignment_target;
mod array_assignment_target_rest;
mod array_binding;
mod array_element_in_expression;
mod array_expression;
mod arrow_expression_in_alternate;
mod arrow_expression_single_param;
mod arrow_in_class_constructor;
mod assign_eval_member_or_computed_expression;
mod assignment_expression;
mod assignment_shorthand_prop_with_initializer;
mod assignment_target;
mod async_arrow_expression;
mod async_continue_statement;
mod async_function_expression;
mod async_ident;
mod async_in_class_constructor;
mod async_method;
mod await_expression;
mod binary_expression;
mod binding_identifier;
mod block_statement;
mod bom_character;
mod break_statement;
mod call_arguments;
mod call_expression;
mod class_declaration;
mod class_empty_element;
mod class_expression;
mod class_member_modifiers;
mod class_member_modifiers_no_asi;
mod class_named_abstract_is_valid_in_js;
mod class_static_constructor_method;
mod computed_member_expression;
mod computed_member_in;
mod computed_member_name_in;
mod conditional_expression;
mod constructor_class_member;
mod continue_statement;
mod debugger_statement;
mod destructuring_initializer_binding;
mod directives;
mod directives_redundant;
mod do_while_statement;
mod empty_statement;
mod exponent_unary_parenthesized;
mod for_await_async_identifier;
mod for_statement;
mod for_with_in_in_parenthesized_expression;
mod function_declaration;
mod function_expression;
mod function_expression_id;
mod function_identifier;
mod getter_class_member;
mod getter_object_member;
mod grouping_expression;
mod hoisted_declaration_in_single_statement_context;
mod identifier;
mod if_statement;
mod labeled_statement;
mod labelled_function_declaration;
mod labelled_statement_in_single_statement_context;
mod lexical_declaration;
mod literals;
mod logical_expression;
mod member_expression;
mod method_class_member;
mod module_export;
mod module_import;
mod new_expression;
mod object_binding;
mod object_expression;
mod object_expression_async_method;
mod object_expression_generator_method;
mod object_expression_method;
mod object_member_name;
mod object_prop_in_rhs;
mod object_prop_name;
mod object_shorthand_property;
mod optional_expression;
mod parameter_list;
mod paren_or_arrow_expression;
mod parenthesized_sequence_expression;
mod pattern_with_default_in_keyword;
mod postfix_expression;
mod prefix_expression;
mod private_name_presence_check;
mod property_assignment_target;
mod property_class_member;
mod rest_property_assignment_target;
mod return_statement;
mod scoped_declarations;
mod script;
mod semicolons;
mod setter_class_member;
mod setter_object_member;
mod single_parameter_arrow_function_with_parameter_named_async;
mod static_generator_constructor_method;
mod static_initialization_block_member;
mod static_member_expression;
mod super_expression;
mod super_expression_in_constructor_parameter_list;
mod switch_statement;
mod template_literal;
mod this_expression;
mod throw_statement;
mod try_statement;
mod unary_delete;
mod unary_delete_nested;
mod unary_expression;
mod while_statement;
mod with_statement;
mod yield_expression;
mod yield_in_generator_function;

// mod class_decorator;
// mod class_await_property_initializer;
// mod decorator_class_declaration;
// mod decorator_class_declaration_top_level;
// mod decorator_export_class_clause;
// mod decorator_export_top_level;
// mod identifier_reference;
// mod in_expression_in_arguments;
// mod decorator_expression_class;
// mod reparse_await_as_identifier;
// mod reparse_yield_as_identifier;
